# This file configures the analyzer for strict type checking and best practices.

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    parameter_assignments: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Error Prevention
    avoid_print: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true

    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # Documentation
    public_member_api_docs: false

    # Immutability
    prefer_const_literals_to_create_immutables: true
    avoid_setters_without_getters: true

    # Type Safety
    always_declare_return_types: true
    always_specify_types: false
    avoid_dynamic_calls: true
    avoid_types_on_closure_parameters: false

    # Clean Code
    unnecessary_lambdas: true
    unnecessary_this: true
    unnecessary_new: true
    unnecessary_const: true
    prefer_is_empty: true
    prefer_is_not_empty: true

    # Async
    unawaited_futures: true
    avoid_void_async: true
